defmodule ExMachina.TestFactory do
  use ExMachina.Ecto, repo: ExMachina.TestRepo

  def custom_factory do
    %ExMachina.Custom{
      non_autogenerated_id: 1,
      name: "Testing"
    }
  end

  def user_factory do
    %ExMachina.User{
      name: "John Doe",
      admin: false,
      articles: [],
    }
  end

  def article_factory do
    %ExMachina.Article{
      title: "My Awesome Article",
      author: build(:user),
    }
  end

  def site_factory do
    %ExMachina.Site{
      name: "My Wonderful Blog"
    }
  end

  def comment_with_embedded_assocs_factory do
    %ExMachina.Comment{}
  end

  def invalid_cast_factory do
    %ExMachina.InvalidCast{}
  end

  def article_for_site_factory do
    %ExMachina.Article{
      site: insert(:site),
      title: "My Awesome Article",
      author: &build(:user, site: &1.site),
    }
  end

  def user_map_factory do
    %{
      id: 3,
      name: "John Doe",
      admin: false
    }
  end
end
